### PR TITLE
Output help to user instead of channel

### PR DESCRIPTION
**Pull request by psykzz**
Output to channel could be quite spammy in some instances.

Outputting the logs to the user would be better and would make them easier to view again instead of recalling the function.

### CODE REVIEW

**Comment by chaos95** [comment]
Definitely agree with the sentiment, although I think this speaks to a larger issue of 'The help system generally sucks' :laughing: 

Thanks for your contributions, they're much appreciated.

**Comment by psykzz** [comment]
Well i would love to put some more time into it and make it work. Just need to find the time :+1:

**Comment by chaos95** [comment]
One thing I would ask with these PRs: our practice on pyGBot is to make all changes on the dev branch and merge into master when we're ready to release (we're _kind of_ following the git-flow practice) so if you could issue the Pull Requests against `dev` instead of `master` it would fit better with our processes. :)

Edit: I should actually make this clearer in the readme :P

**Comment by psykzz** [comment]
Will do, my bad.

**Comment by psykzz** [comment]
Updated the base branch to dev, can this be merged?

**Pull request merged**
